### ISSUE TITLE
Incorrect formatting

### ISSUE THREAD

**Issue by springimport** [bobsta63/netbeans-psr-formatting#13] opened 2017-02-17 18:42 UTC
Please, fix this.

Example:
```php
    /**
     * Constructor
     * 
     * @param \Magento\Framework\App\Helper\Context $context
     * @param \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig
     * @param \Magento\Customer\Model\Session $customerSession
     */
    public function __construct(
    \Magento\Framework\App\Helper\Context $context, \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig, \Magento\Customer\Model\Session $customerSession
    )
    {
        $this->_scopeConfig = $scopeConfig;
        $this->customerSession = $customerSession;
        $this->isEnabled = $this->_scopeConfig->getValue(self::XML_CONFIG_ENABLE);
        parent::__construct($context);
    }
```
↓
```php
    /**
     * Constructor
     * 
     * @param \Magento\Framework\App\Helper\Context $context
     * @param \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig
     * @param \Magento\Customer\Model\Session $customerSession
     */
    public function __construct(
        \Magento\Framework\App\Helper\Context $context,
        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
        \Magento\Customer\Model\Session $customerSession
    ) {
        $this->_scopeConfig = $scopeConfig;
        $this->customerSession = $customerSession;
        $this->isEnabled = $this->_scopeConfig->getValue(self::XML_CONFIG_ENABLE);
        parent::__construct($context);
    }
```

PSR:
```php
<?php
namespace Vendor\Package;

class ClassName
{
    public function aVeryLongMethodName(
        ClassTypeHint $arg1,
        &$arg2,
        array $arg3 = []
    ) {
        // method body
    }
}
```
> When the argument list is split across multiple lines, the closing parenthesis and opening brace MUST be placed together on their own line with one space between them.

http://www.php-fig.org/psr/psr-2/#method-arguments

**Comment by allebb** [comment] 2017-02-17 19:49
I'm pretty sure that this is a limitation of NetBeans... If however, they've recently fixed it in 8.2 and you've been able to manually specify the option please could you let me know which one and I will be able to add it to the package.

Otherwise I'll get round to doing further investigation when I'm back from my holiday. - Happy to accept any PR's too :)

**Comment by shawe** [comment] 2017-07-01 10:27
@springimport Seems that also you are not using http://www.php-fig.org/psr/psr-2/#namespace-and-use-declarations

> When present, all use declarations MUST go after the namespace declaration.

     * @param \Magento\Framework\App\Helper\Context $context
     * @param \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig
     * @param \Magento\Customer\Model\Session $customerSession

And you are putting it on phpdoc block, where is not needed if you put it as expected.

**Comment by allebb** [comment] 2017-07-05 09:41
👍 

Closing issue as I cannot reproduce, the advice offered by @shawe seems to do the trick.

**Closed as completed by allebb** 2017-07-05 09:41 UTC

**Comment by shawe** [comment] 2017-07-08 10:38
@allebb for me using PhpStorm, yes, do the trick, but NetBeans seems to have a very poor support respecting for PSR1/PSR2 rules.
